name: CI/CD Workflow

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose  # Install Docker Compose

    - name: Install Pipenv
      run: pip install pipenv
    
    - name: Create shared network
      run: docker network create shared_network

    - name: Start Docker services
      run: |
        docker-compose --env-file mlflow.env -f mlflow.docker-compose.yml up -d
        docker-compose -f src/web_service/web-service.docker-compose.yml up -d

    - name: Wait for services to be ready
      run: sleep 20  # Adjust as necessary for services to fully start

    - name: Install dependencies from Pipfile
      working-directory: src/web_service/fastapi
      run: pipenv install 

    - name: Run FastAPI unit tests
      working-directory: src/web_service/fastapi
      run: pipenv run pytest tests/unit

    - name: Stop Docker services
      run: |
        docker-compose -f mlflow.docker-compose.yml down
        docker-compose -f src/web_service/web-service.docker-compose.yml down
